- name: Variables
  hosts: web
  vars:
    course: DevOps
    name: Rajasekhar
    duration: 3.5 months

  tasks:
  - name: Print the information
    ansible.builtin.debug:
      msg: "Hello I am learning {{course}} from trainer {{name}} and durration is {{duration}}"