- name: Variables from file
  hosts: web
  vars_files: # calling variables from file
  - variables.yaml

  tasks:
  - name: Print the information
    ansible.builtin.debug:
      msg: "Hellow, I am learning {{course}} from trainer {{trainer}} and duration is {{duration}}"