- name: calling variable from file
  hosts: web
  vars_file:
  - varables.yaml

  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hellow, I am learning {{course}} from trainer {{trainer}} and duration is {{duration}}"
