- name: Different types of Data Types
  hosts: localhost

  vars:
   course: "DevOps with AWS"  # this type is called string
   tools:                     # this type is called list
    - Linux
    - Shell
    - Ansible
   experiance:                # this type we can called map or dictionary
    DevOps: 3                 # number
    AWS: 2
    Docker: 1
  # RealProject: true          # boolen

  tasks:
  - name: Print the information
    ansible.builtin.debug:
      msg: > 
        Course: {{ course }}, 
        Tools covered: {{ tools }}, 
        Experience is: {{ experiance }}, 
      # is it Real Project {{ RealProject }}