- name: conditions
  hosts: web

# This example runs some_command (id expense) and registers the result in the variable command_result (USER).
# If the return code (rc) is not zero, the playbook will fail with a message indicating the error.

tasks:
  - name: check user exits or not
      ansible.builtin.command: id expense
    # "ansible.builtin.command" by using this we can execute commands directly in play books
      register: USER
    # "register" keyword is to capture the result of above task.

  - name: Check the command result
  fail:
    msg: "The command failed with exit status {{ USER.rc }}"
  when: USER.rc != 0

  - name: print user information
    ansible.builtin.debug:
      msg: "User info: {{USER}}"

  - name: create user if not exists
    ansible.builtin.command: useradd expense
    when: USER.rc ! = 0 

# In this playbook:
# The command module runs some_command and stores the result in command_result.
# The fail module checks if command_result.rc is not zero and fails the playbook with a custom message if the command failed.
# A debug task demonstrates how you can conditionally perform other tasks based on the success or failure of the command.