- name: check number
  hosts: localhost

  vars_prompt: # prompts are always considered as text/string
  - name: number
    prompt: Please enter number
    private: false

# Ansible is strict, it can't automatically convert text into number
# 10 --> text
# if you give other than number then it will treat as zero

  tasks:
  - name: number is less than 10
    ansible.builtin.debug:
      msg: "Given number is {{ number }} less than 10"
    when: number | int < 10
    # filter is denoted by | (pipe symbol)

  - name: number is greater than or equal to 10
    ansible.builtin.debug:
      msg: "Given number is {{ number }} greater than or equal to 10"
    when: number | int >= 10


# - hosts: localhost
#   vars_prompt:
#     name: number
#     prompt: Please enter number

#   tasks:
#     - name: Check if the variable is an integer and greater than or equal to 10
#       debug:
#         msg: "The variable is an integer and is greater than or equal to 10."
#       when: number is int and number >= 10

#     - name: Variable is either not an integer or less than 10
#       debug:
#         msg: "The variable is either not an integer or less than 10."
#       when: not (number is int and number >= 10)

# In this playbook, The variable number is defined. 
# The first task checks if number is an integer and greater than or equal to 10.
# The second task runs if the first condition is not met, indicating that number is either not an integer or less than 10