- name: install packages
  hosts: web
  become: yes

  tasks:
  - name: install packages
    loop:
    - mysql
    - nginx
    - postfix
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
